### ISSUE TITLE
[Spike]: Investigate current FTP server

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [ZinkNotTheMetal/tennessee-game-days#102]
### New feature you are looking for

Details in my vault

### Any additional context or links?

Look at transactions.log
Look at transactions.csv

Investigate other files on the web server, also understand if we can test registration before it goes live

**Comment by stanbery** [comment]
Transactions of both sorts, plus individuals, is handled by PHP and should not be something to process in the future, we hope.

**Comment by ZinkNotTheMetal** [comment]
@stanbery, do you feel like you have a good understanding of the hosting environment?
Do you have any other questions we need to ask before I close this?

**Comment by stanbery** [comment]
Only thing I'd like to figure out is the hosting database situation - that's likely a conversation with Hatch or Bo?
