### ISSUE TITLE
[Feature]: Lists should have "static" column headers at the top

### ISSUE THREAD

**Issue by stanbery** [ZinkNotTheMetal/tennessee-game-days#151]
### New feature you are looking for

When lists are provided, the column headers should remain at the top of the screen always - they shouldn't scroll off when going down the list, to allow filtering/sorting of columns.

**Comment by ZinkNotTheMetal** [comment]
I can do that, but what does sorting do if the header is at the top. It will jump around your current list.

What about a floating back to top button? Would that be sufficient?

**Comment by ZinkNotTheMetal** [comment]
Freeze header if possible
